[tool.black]
line-length = 80

[tool.isort]
profile = "black"
line_length = 80
sections = ["FUTURE", "STDLIB", "FIRSTPARTY", "THIRDPARTY", "LOCALFOLDER"]


[project]

dependencies = [
    dlt[filesystem,postgres]>=1.12.3
        dlt[postgres]>=1.12.3
        dlt[filesystem]>=1.12.3

]
